parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jisc\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Command/AbstractCommand.php}'